// <auto-generated />
using System;
using CitiesManager.Web.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.Web.Migrations
{
    [DbContext(typeof(CitiesDbContext))]
    [Migration("20251006144926_seeding cities")]
    partial class seedingcities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.Web.Models.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("21d68aa7-7214-4194-9662-95703ea61d4b"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityID = new Guid("92cb40db-a930-482f-84c0-4d1538a01cc4"),
                            CityName = "London"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
